<a href="https://colab.research.google.com/github/skimaza/assist_ai/blob/main/tensor_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 참고 문서
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py   
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html  


Deep Learning with PyTorch


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch

In [2]:
print(torch.cuda.is_available())

True


<font color='red'> **주의) 위 결과가 False이면 Colab 메뉴의 런타임->런타임 유형변경에서 하드웨어 가속기를 GPU로 선택하고 다시 시작**</font>

In [3]:
x = torch.empty(5, 3) # 5행, 3열의 텐서. 값은 모두 garbage
print(x)

tensor([[-3.0226e+35,  3.0672e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22,  0.0000e+00]])


In [4]:
print(x.size()) # size, shape

torch.Size([5, 3])


In [5]:
print(x.shape)

torch.Size([5, 3])


<div class="alert alert-info"><h1>Uninitialized vs random</h1><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>


---




torch.empty는 초기화하지 않은 값(할당받은 메모리에 있는 값)이 들어있다

Construct a 5x3 matrix, uninitialized:

즉 값이 garbage임. random이 아님.



In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[-3.0226e+35,  3.0672e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 4.4721e+21,  1.5956e+25,  4.7399e+16],
        [ 3.7293e-08,  3.9664e+28,  6.9397e+22],
        [ 1.7260e+25,  2.2856e+20,  5.0948e-14]])


In [7]:
print(torch.get_default_dtype())

torch.float32


In [8]:
print(x.dtype)

torch.float32


torch.empty는 torch의 global default dtype 이면서 garbage 값을 가지는 원소가 채워진 텐서를 생성.

즉 디폴트 타입을 갖는 빈 텐서를 생성.

In [9]:
x = torch.FloatTensor(5,3)
print(x)

tensor([[-3.0226e+35,  3.0672e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  7.1547e+22],
        [ 1.3733e-14,  6.4069e+02,  4.3066e+21],
        [ 1.1824e+22,  4.3066e+21,  6.3828e+28],
        [ 3.8016e-39,  0.0000e+00,  0.0000e+00]])


<h1>주의) torch.Tensor와 torch.tensor 사용 예.</h1>

torch.Tensor는 Tensor 클래스를 instantiation. 즉 torch.empty와 같은 동작.

torch.tensor는 인자로 받는 데이터 값을 복제. 인자는 리스트, 튜플, ndarray, 스칼라 값 등 다양한 형태. 텐서를 만드는 가장 일반적 형태임.

In [10]:
x = torch.Tensor(5,3)
print(x, x.dtype) # 의미없는 값.

tensor([[-3.0226e+35,  3.0672e-41,  2.3694e-38],
        [ 9.2196e-41, -3.0226e+35,  3.0672e-41],
        [-3.0478e+35,  3.0672e-41, -3.1655e+35],
        [ 3.0672e-41, -3.1656e+35,  3.0672e-41],
        [-3.1655e+35,  3.0672e-41,  0.0000e+00]]) torch.float32


In [11]:
x = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print(x, x.dtype)

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]]) torch.float32


In [12]:
x = torch.tensor([0, 1]) # dtype을 인자의 값에서 유추하여 설정
print(x, x.dtype) 

tensor([0, 1]) torch.int64


In [13]:
y = torch.tensor([0.0, 1.0])
print(y, y.dtype)

tensor([0., 1.]) torch.float32


In [14]:
try:
    z = torch.tensor([[0.11111, 0.222222, 0.3333333]], dtype=torch.float64, device=torch.device('cuda:0'))  # creates a torch.cuda.DoubleTensor
    print(z, z.dtype)
except Exception as e:
    print('Error:', e)

tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64) torch.float64


CPU 환경에선 위 문장이 오류 발생.

GPU 환경으로 런타임 변경 후 실행.



In [15]:
x = torch.tensor(3.14159)  # Create a scalar (zero-dimensional tensor)
print(x, x.dtype)

tensor(3.1416) torch.float32


In [16]:
x = torch.tensor([])  # Create an empty tensor (of size (0,))
print(x, x.dtype)

tensor([]) torch.float32


In [17]:
try:
    x = torch.tensor(3,2) # 인자가 매치하지 않으므로 오류가 나야 함.
    print(x, x.dtype)
except Exception as e:
    print('Error:', e)

Error: tensor() takes 1 positional argument but 2 were given




---



<h1>Random</h1>
Construct a randomly initialized matrix:



In [18]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6106, 0.1358, 0.2298],
        [0.4580, 0.9274, 0.1602],
        [0.1059, 0.0834, 0.8331],
        [0.0217, 0.5579, 0.4679],
        [0.8884, 0.5640, 0.5379]])


Construct a matrix filled zeros and of dtype long:



In [19]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


<h1>데이터를 인자로 주어 텐서 생성</h1>
Construct a tensor directly from data:



In [20]:
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



x와 같은 타입의 새 텐서 생성

In [21]:
x  = x.new_ones(5, 3)      # new_* methods take in sizes
print(x, x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [22]:
x  = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x, x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.float64


In [23]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x, x.dtype)                                      # result has the same size

tensor([[ 0.8815, -0.4184,  0.0153],
        [-0.1281, -0.1178,  0.4411],
        [ 1.3856,  0.2023, -0.7654],
        [-1.6897,  0.8962,  0.8546],
        [ 0.8858, -1.1012,  0.8380]]) torch.float32


Get its size: size() or shape



In [24]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

<h1>텐서 더하기</h1>

Addition: syntax 1



In [25]:
y = torch.rand(5, 3)
print('x\n', x)
print('y\n', y)
print('x+y\n', x + y)

x
 tensor([[ 0.8815, -0.4184,  0.0153],
        [-0.1281, -0.1178,  0.4411],
        [ 1.3856,  0.2023, -0.7654],
        [-1.6897,  0.8962,  0.8546],
        [ 0.8858, -1.1012,  0.8380]])
y
 tensor([[0.2691, 0.3013, 0.0288],
        [0.3602, 0.8997, 0.1451],
        [0.0238, 0.5176, 0.7644],
        [0.1169, 0.9153, 0.7058],
        [0.3358, 0.9711, 0.0666]])
x+y
 tensor([[ 1.1506e+00, -1.1708e-01,  4.4037e-02],
        [ 2.3207e-01,  7.8194e-01,  5.8625e-01],
        [ 1.4095e+00,  7.1991e-01, -1.0388e-03],
        [-1.5728e+00,  1.8116e+00,  1.5604e+00],
        [ 1.2216e+00, -1.3014e-01,  9.0465e-01]])


Addition: syntax 2



In [26]:
print(torch.add(x, y))

tensor([[ 1.1506e+00, -1.1708e-01,  4.4037e-02],
        [ 2.3207e-01,  7.8194e-01,  5.8625e-01],
        [ 1.4095e+00,  7.1991e-01, -1.0388e-03],
        [-1.5728e+00,  1.8116e+00,  1.5604e+00],
        [ 1.2216e+00, -1.3014e-01,  9.0465e-01]])


Addition: providing an output tensor as argument



In [27]:
result = torch.empty(5, 3)
print(result)

tensor([[ 2.8641e+08,  3.0673e-41,  4.4037e-02],
        [ 2.3207e-01,  7.8194e-01,  5.8625e-01],
        [ 1.4095e+00,  7.1991e-01, -1.0388e-03],
        [-1.5728e+00,  1.8116e+00,  1.5604e+00],
        [ 1.2216e+00, -1.3014e-01,  9.0465e-01]])


In [28]:
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1506e+00, -1.1708e-01,  4.4037e-02],
        [ 2.3207e-01,  7.8194e-01,  5.8625e-01],
        [ 1.4095e+00,  7.1991e-01, -1.0388e-03],
        [-1.5728e+00,  1.8116e+00,  1.5604e+00],
        [ 1.2216e+00, -1.3014e-01,  9.0465e-01]])


In [29]:
res = x + y
print(res)

tensor([[ 1.1506e+00, -1.1708e-01,  4.4037e-02],
        [ 2.3207e-01,  7.8194e-01,  5.8625e-01],
        [ 1.4095e+00,  7.1991e-01, -1.0388e-03],
        [-1.5728e+00,  1.8116e+00,  1.5604e+00],
        [ 1.2216e+00, -1.3014e-01,  9.0465e-01]])


Addition: in-place



In [30]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1506e+00, -1.1708e-01,  4.4037e-02],
        [ 2.3207e-01,  7.8194e-01,  5.8625e-01],
        [ 1.4095e+00,  7.1991e-01, -1.0388e-03],
        [-1.5728e+00,  1.8116e+00,  1.5604e+00],
        [ 1.2216e+00, -1.3014e-01,  9.0465e-01]])


# **_로 끝나는 operation은 in-place**
<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!





# autograd

학습에서 error backpropagation을 위한 그래디언트 계산을 자동화한 PyTorch 기능

In [31]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [32]:
a

tensor([2., 3.], requires_grad=True)

In [33]:
b

tensor([6., 4.], requires_grad=True)

In [34]:
Q = 3*a**3 - b**2

\begin{align}Q=3a^{3}-b^{3}\end{align}

In [35]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

\begin{align}\frac{\partial Q}{\partial a} = 9a^2\end{align}

\begin{align}\frac{\partial Q}{\partial b} = -2b\end{align}

\begin{align}\frac{dQ}{dQ} = 1\end{align}

In [36]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [37]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [38]:
a.grad, b.grad

(tensor([36., 81.]), tensor([-12.,  -8.]))

In [39]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


# 일반적으로는 Numpy 배열과 유사한 신택스를 가진다

# Indexing tensors

## Python slicing 과 유사

https://drive.google.com/file/d/1qYbFGElZiXcB4VgUiolBp0f2YZS1pzGw/view?usp=sharing



In [40]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [41]:
print(some_list[1:4])
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1])
print(some_list[1:4:2]) # 1 to 3 ([1,2,3]), step 2 ([1,3])

[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points.shape)


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])


In [43]:
print(points[1:])

tensor([[5., 3.],
        [2., 1.]])


In [44]:
print(points[1:, :])

tensor([[5., 3.],
        [2., 1.]])


In [45]:
print(points[1:, 0])

tensor([5., 2.])


In [46]:
print(points[None])

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [47]:
print(points[None].size())

torch.Size([1, 3, 2])


In [49]:
points.shape

torch.Size([3, 2])

In [50]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

# unsqueeze - dimension 확장. dim으로 지정된 디멘션을 하나 확장

In [51]:
print(points.unsqueeze(dim=0))
print(points.unsqueeze(dim=0).size())

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])
torch.Size([1, 3, 2])


In [52]:
unsq_points = points.unsqueeze(dim=0)
print(unsq_points)
print(unsq_points.size())

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])
torch.Size([1, 3, 2])


# squeeze - dimension 축소
### 원소 1개짜리 dimension을 제거

In [53]:
sq_points = unsq_points.squeeze()
print(sq_points)
print(sq_points.size())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])




---

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



x는 (4,4), y는 (16,), z는 (inferred, 8)인데 전체가 16 원소이므로 inferred는 2가 되어 (2,8)

In [55]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print('x.size()=', x.size(), '\ny.size()=', y.size(), '\nz.size()=', z.size())
print(x, '\n', y, '\n', z)

x.size()= torch.Size([4, 4]) 
y.size()= torch.Size([16]) 
z.size()= torch.Size([2, 8])
tensor([[-0.3112, -0.8315,  2.0023, -0.8920],
        [-0.7311, -0.1806, -1.3087, -0.4823],
        [ 1.4226, -2.2820, -0.0773, -2.7146],
        [ 1.2870,  1.0097,  0.1546,  1.3778]]) 
 tensor([-0.3112, -0.8315,  2.0023, -0.8920, -0.7311, -0.1806, -1.3087, -0.4823,
         1.4226, -2.2820, -0.0773, -2.7146,  1.2870,  1.0097,  0.1546,  1.3778]) 
 tensor([[-0.3112, -0.8315,  2.0023, -0.8920, -0.7311, -0.1806, -1.3087, -0.4823],
        [ 1.4226, -2.2820, -0.0773, -2.7146,  1.2870,  1.0097,  0.1546,  1.3778]])


---
# transpose

In [56]:
points = torch.tensor([[3.0, 1.0, 2.0], [4.0, 1.0, 7.0]])
print(points)

tensor([[3., 1., 2.],
        [4., 1., 7.]])


## 서로 바꿀 두 디멘션을 지정

In [57]:
points_tr = points.transpose(0, 1)

In [58]:
points_tr

tensor([[3., 4.],
        [1., 1.],
        [2., 7.]])

In [59]:
points

tensor([[3., 1., 2.],
        [4., 1., 7.]])

In [60]:
points_t = points.t() # 2D or less dimension
print(points_t)

tensor([[3., 4.],
        [1., 1.],
        [2., 7.]])


## Multidimensional

In [61]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2) # 0번째와 2번째 디멘션을 transpose
some_t.shape

torch.Size([3, 4, 5])

In [62]:
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [63]:
transpose_t.shape

torch.Size([5, 4, 3])

# Contiguous

가장 오른쪽 차원이 순차적으로 저장된 텐서

In [64]:
some_t.is_contiguous()

True

continous한 텐서의 transpose는 실제 데이터를 옮기는 것이 아니라 접근하는 방법만 다르게 하기 때문에 continous하지 않음

In [66]:
transpose_t.is_contiguous()

False

## Contiguous로 변환하기

In [67]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [68]:
points_t = points.t()

In [69]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [70]:
points_t.is_contiguous()

False

실제 데이터를 contiguous하게 재배치

In [72]:
points_t_cont = points_t.contiguous()

In [73]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [74]:
points_t_cont.contiguous()

tensor([[4., 5., 2.],
        [1., 3., 1.]])

## tensor view()

같은 storage 에서 보는 관점 (shape)만 다르게 함

In [75]:
t = torch.rand(4, 4)
b = t.view(2, 8)
print(t, t.shape)
print(b, b.shape)

tensor([[0.4407, 0.9571, 0.6890, 0.5465],
        [0.2858, 0.9516, 0.4148, 0.6201],
        [0.9849, 0.9962, 0.1261, 0.0170],
        [0.2510, 0.7078, 0.5342, 0.2367]]) torch.Size([4, 4])
tensor([[0.4407, 0.9571, 0.6890, 0.5465, 0.2858, 0.9516, 0.4148, 0.6201],
        [0.9849, 0.9962, 0.1261, 0.0170, 0.2510, 0.7078, 0.5342, 0.2367]]) torch.Size([2, 8])


In [76]:
t.is_contiguous()

True

In [77]:
b.is_contiguous()

True

## view 같은 operation은 contiguous tensor에서만 동작

In [78]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [79]:
x.shape

torch.Size([2, 3])

In [80]:
x_t = x.t()
x_t

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [81]:
y = x.view(3,2) # transpose가 아님
y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [82]:
y.is_contiguous()

True

In [83]:
x_t.is_contiguous()

False

contiguous하지 않은 텐서로 view를 부르면 오류가 발생

In [87]:
try:
    x_t.view(2, 3) # error
except Exception as e:
    print('Error:', e)

Error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [88]:
x_t_cont = x_t.contiguous()
x_t_cont

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [89]:
x_t_cont.view(2, 3)

tensor([[1, 4, 2],
        [5, 3, 6]])

In [90]:
x_t

tensor([[1, 4],
        [2, 5],
        [3, 6]])

x_t와 x_t_cont는 표시되는 값은 같으나 내부의 데이터 순서가 다르게 배치되어 있음

In [91]:
x = torch.randn(2,3,4)
x_t = x.transpose(0, 2)
print(x.shape)
print(x_t.shape)


torch.Size([2, 3, 4])
torch.Size([4, 3, 2])


In [92]:
x

tensor([[[-0.0203,  1.4557,  0.6741, -0.9552],
         [ 0.5372,  1.0151,  1.3597,  0.4710],
         [-1.3028, -0.1712, -0.4442, -0.3842]],

        [[ 0.8422, -0.2642,  0.1464, -0.7503],
         [-0.7967,  1.5664, -1.2226, -1.3853],
         [ 0.3374, -1.1332, -0.7648,  0.3682]]])

In [93]:
x.view(2, 12)

tensor([[-0.0203,  1.4557,  0.6741, -0.9552,  0.5372,  1.0151,  1.3597,  0.4710,
         -1.3028, -0.1712, -0.4442, -0.3842],
        [ 0.8422, -0.2642,  0.1464, -0.7503, -0.7967,  1.5664, -1.2226, -1.3853,
          0.3374, -1.1332, -0.7648,  0.3682]])

In [94]:
try:
    x_t.view(4,6) # Error
except Exception as e:
    print('Error:', e)

Error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


## reshape()

In [95]:
y = x.reshape((2, 12))

In [96]:
print(y.size())
y

torch.Size([2, 12])


tensor([[-0.0203,  1.4557,  0.6741, -0.9552,  0.5372,  1.0151,  1.3597,  0.4710,
         -1.3028, -0.1712, -0.4442, -0.3842],
        [ 0.8422, -0.2642,  0.1464, -0.7503, -0.7967,  1.5664, -1.2226, -1.3853,
          0.3374, -1.1332, -0.7648,  0.3682]])

In [97]:
z = x.reshape((6, -1)) # -1 은 알아서 맞추라는 의미

In [98]:
z

tensor([[-0.0203,  1.4557,  0.6741, -0.9552],
        [ 0.5372,  1.0151,  1.3597,  0.4710],
        [-1.3028, -0.1712, -0.4442, -0.3842],
        [ 0.8422, -0.2642,  0.1464, -0.7503],
        [-0.7967,  1.5664, -1.2226, -1.3853],
        [ 0.3374, -1.1332, -0.7648,  0.3682]])

In [99]:
z = x.reshape((3, -1))

In [100]:
z

tensor([[-0.0203,  1.4557,  0.6741, -0.9552,  0.5372,  1.0151,  1.3597,  0.4710],
        [-1.3028, -0.1712, -0.4442, -0.3842,  0.8422, -0.2642,  0.1464, -0.7503],
        [-0.7967,  1.5664, -1.2226, -1.3853,  0.3374, -1.1332, -0.7648,  0.3682]])

In [101]:
y = x.reshape((-1, 2))

In [102]:
y

tensor([[-0.0203,  1.4557],
        [ 0.6741, -0.9552],
        [ 0.5372,  1.0151],
        [ 1.3597,  0.4710],
        [-1.3028, -0.1712],
        [-0.4442, -0.3842],
        [ 0.8422, -0.2642],
        [ 0.1464, -0.7503],
        [-0.7967,  1.5664],
        [-1.2226, -1.3853],
        [ 0.3374, -1.1332],
        [-0.7648,  0.3682]])


NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

## The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [103]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [104]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [105]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [106]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.dtype, z.device)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
    print(z.device)

tensor([[[ 0.9797,  2.4557,  1.6741,  0.0448],
         [ 1.5372,  2.0151,  2.3597,  1.4710],
         [-0.3028,  0.8288,  0.5558,  0.6158]],

        [[ 1.8422,  0.7358,  1.1464,  0.2497],
         [ 0.2033,  2.5664, -0.2226, -0.3853],
         [ 1.3374, -0.1332,  0.2352,  1.3682]]], device='cuda:0')
torch.float32 cuda:0
tensor([[[ 0.9797,  2.4557,  1.6741,  0.0448],
         [ 1.5372,  2.0151,  2.3597,  1.4710],
         [-0.3028,  0.8288,  0.5558,  0.6158]],

        [[ 1.8422,  0.7358,  1.1464,  0.2497],
         [ 0.2033,  2.5664, -0.2226, -0.3853],
         [ 1.3374, -0.1332,  0.2352,  1.3682]]], dtype=torch.float64)
cuda:0


In [107]:
print(z.to("cpu").dtype)

torch.float32


In [108]:
print(z.to("cpu").device)

cpu
